# Generated by Django 4.0.4 on 2022-05-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product_image1_product_image2_product_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_Image',
            field=models.ImageField(blank='True', null='True', upload_to='categorypics'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='product',
            name='featured_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='subcategory_Image',
            field=models.ImageField(blank='True', null='True', upload_to='subcategorypics'),
            preserve_default='True',
        ),
    ]
