# Generated by Django 4.0.4 on 2022-05-14 00:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_product_creation_date_product_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
