# Generated by Django 4.0.4 on 2022-05-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_order_orderdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='received', max_length=10),
        ),
    ]
